Team/3
nuta312/TalentLMSFall2023 pull request #34
Opened 2024-02-21 15:37 UTC by LiZhazgul

Прошу проверить, Java версию поменяли на 17.

2024-02-21 15:40 UTC, NurzatBekeshev commented on src/main/java/pages/AddUserTypePage.java
> +public class AddUserTypePage extends BasePage {
пробел перед сигнатурой класса и после класса (опционально)

2024-02-21 15:40 UTC, NurzatBekeshev commented on src/main/java/pages/AddUserTypePage.java
> +    public WebElement arrowClickInput;//галочку нажимаем где находиться Administrator,Instructor,Learner
комментарии такие лишние

2024-02-21 15:43 UTC, NurzatBekeshev commented on src/main/java/pages/AddUserTypePage.java
> +    public AddUserTypePage learnerClick() {       // по очереди запускаем
комментарии лишние, есть другой формат

2024-02-21 15:43 UTC, NurzatBekeshev commented on src/main/java/pages/ExportPage.java
> +    @FindBy(xpath = "//a[normalize-space()='Export']")
Также пробелы

2024-02-21 15:45 UTC, NurzatBekeshev commented on src/main/java/pages/LoginPage.java
> +    public LoginPage fillLogin(){
Просили изменить название, типа doLogin

2024-02-21 15:46 UTC, NurzatBekeshev commented on src/main/java/pages/UserTypesPage.java
> +    }
лишние пробелы внутри метода можно убрать

2024-02-21 15:47 UTC, NurzatBekeshev commented on src/main/java/pages/UserTypesPage.java
> +
пробел

2024-02-21 15:48 UTC, NurzatBekeshev commented on src/main/java/entity/User.java
>  import lombok.Data;
Добавьте аннотации lombok по отдельности, не Data

2024-02-21 15:49 UTC, NurzatBekeshev commented on src/test/java/uiTest/AddUserTypeTest.java
> +import org.testng.annotations.Test;
пробел перед статик импортом

2024-02-21 15:49 UTC, NurzatBekeshev commented on src/test/java/uiTest/AddUserTypeTest.java
> +    @Test(description = "Add a user type.Type user role defaults with the assert")
это UserPage, не тест, тесты в package test

2024-02-21 15:51 UTC, NurzatBekeshev commented on src/test/java/uiTest/BaseTest.java
> +import pages.*;
* в импорты не ставится

2024-02-21 15:51 UTC, NurzatBekeshev commented on src/test/java/uiTest/BaseTest.java
> +import pages.reports.*;
также звездочка

2024-02-21 15:52 UTC, NurzatBekeshev commented on src/test/java/uiTest/ExportTest.java
> +
лишние пробелы

2024-02-21 15:52 UTC, NurzatBekeshev commented on src/test/java/uiTest/UserTypesTest.java
> +
лишний пробел

2024-02-21 15:52 UTC, NurzatBekeshev commented on src/test/java/uiTest/UserTypesTest.java
> +    }
лишние пробелы

2024-02-21 15:52 UTC, NurzatBekeshev commented on src/test/java/uiTest/UserTypesTest.java
> +        Assert.assertEquals(userTypesPage.countingRowsInTable(listUserTypes, searchWord) == listUserTypes.size(), true);
Также лишние

2024-02-21 15:54 UTC, NurzatBekeshev requested changes
Что изменить: fillLogin, * в импортах, пробелы

2024-02-22 02:55 UTC, TimurTester reviewed
Добрый день. Код исправлен по данным комментариям. Прошу внимательно проверить и дать обратную связь.

2024-02-22 03:23 UTC, NurzatBekeshev commented on src/main/java/entity/User.java
> +import lombok.*;
Также можете звездочку заменить на точные импорты

2024-02-22 03:24 UTC, NurzatBekeshev commented on src/main/java/entity/User.java
> +@RequiredArgsConstructor
RequiredArgsConstructor думаю лучше заменить на AllArgsConstructor. Почитать: https://www.kapresoft.com/java/2023/03/30/lombok-allargsconstructor-vs-requiredargsconstructor.html

2024-02-22 03:26 UTC, NurzatBekeshev commented on src/main/java/pages/ExportPage.java
> +    public WebElement ExportTypeFind;
названия переменных с малого регистра

2024-02-22 03:26 UTC, BaiamanA commented on src/main/java/pages/LoginPage.java
> -
должна быть одна пустая строка между статическим и простым import oм

2024-02-22 03:30 UTC, BaiamanA commented on src/main/java/pages/reports/ReportsPage.java
> +
лишняя пустая строка

2024-02-22 03:30 UTC, NurzatBekeshev commented on src/main/java/pages/reports/CoursesUnderReportsPage.java
> +import pages.*;
Звездочка в импорте

2024-02-22 03:30 UTC, NurzatBekeshev commented on src/main/java/pages/reports/ReportsIconAndLinkPage.java
> +import pages.*;
Также звездочка

2024-02-22 03:31 UTC, NurzatBekeshev commented on src/main/java/pages/reports/ReportsIconAndLinkPage.java
> +
Лишние пробелы

2024-02-22 03:32 UTC, NurzatBekeshev commented on src/main/java/pages/reports/ReportsPage.java
> +import pages.*;
Также звездочка

2024-02-22 03:32 UTC, NurzatBekeshev commented on src/main/java/pages/reports/ReportsPage.java
> +import org.openqa.selenium.*;
Звездочка

2024-02-22 03:33 UTC, NurzatBekeshev commented on src/main/java/pages/reports/ReportsPage.java
> +
Пробел лишний. Также получится обойтись тут без Thread.sleep?

2024-02-22 03:33 UTC, NurzatBekeshev commented on src/main/java/pages/reports/TrainingMatrixPage.java
> +import pages.*;
Звездочка

2024-02-22 03:34 UTC, NurzatBekeshev commented on src/main/java/pages/reports/UsersUnderReportsPage.java
> +import pages.*;
Поправьте звездочку)

2024-02-22 03:39 UTC, NurzatBekeshev commented on src/test/java/uiTest/UserTypesTest.java
> +        Thread.sleep(1000);
Можно ли обойтись без Thread.sleep?

2024-02-22 03:51 UTC, NurzatBekeshev requested changes
В коде всё ок, пройдитесь еще раз и поправьте:
- правильные аннотации в классе User (и точные импорты)
- импорты во всех классах и * в них
- Там где возможно, обойдитесь без Thread.sleep в методах и тестах, пожалуйста
- Немного лишних пробелов исправить

2024-02-22 08:07 UTC, LiZhazgul commented
Если ничего серьезного может мержить будем ?))

2024-02-22 08:10 UTC, TimurTester commented
Добрый день, подправил код по комментариям, прошу проверить, должно быть в порядке

2024-02-22 08:21 UTC, TimurTester commented
Прошу прощения, исправил import.pages.* в BaseTest

2024-02-22 09:18 UTC, NurzatBekeshev approved these changes
Good job!

2024-02-22 09:28 UTC, BaiamanA approved these changes

2024-02-22 11:17 UTC, AizhanATA approved these changes

2024-02-22 11:19 UTC, merged